### CREATE AN ACCOUNT
POST http://localhost:8080/accounts
Content-Type: application/json

{
    "owner": "Olubo Ifeoluwa",
    "currency": "USD"
}

### GET AN ACCOUNT
GET http://localhost:8080/accounts/1
Content-Type: application/json

### GET ALL ACCOUNTS WITH PAGINATION
GET http://localhost:8080/accounts?page_size=20&page_number=5
Content-Type: application/json

